### ISSUE TITLE
Call to require tramp-loaddefs takes 30s

### ISSUE THREAD

**Issue by noxecane** [proofit404/pythonic#1]
You would know the root of this issue from [here](https://github.com/proofit404/pyenv-mode/issues/26). Using benchmark-init I was able to notice the require call to `tramp-loaddefs` taking as much as `30s` as you would see in this photo.
![screenshot from 2016-07-26 06-35-01](https://cloud.githubusercontent.com/assets/4183766/17127254/be58a93e-52f3-11e6-95ba-5f70c1f0fb65.png)

**Comment by proofit404** [comment]
I don't know this issue related to my package since it only use tramp as it is. I don't know how to tune this performance.

**Comment by noxecane** [comment]
You are not the only one...[spacemacs is also facing it](http://spacemacs.org/doc/FAQ.html#orgheadline14)

**Comment by proofit404** [comment]
That makes sense. Thanks!
