### ISSUE TITLE
pythonic-activate fails; Cannot open load file: No such file or directory, f

### ISSUE THREAD

**Issue by kidmose** [proofit404/pythonic#16]
Hi all, 

I'm trying to use `pyenv-mode` in emacs 25.2.2 on Linux Mint 19.1, but is fails with the messsage: `Cannot open load file: No such file or directory, f`.
Trying to dig around I find that `pythonic-activate` gives the same error.

Could you provide any suggestion as to how to fix `pythonic-activate`?
(elisp noob here, so detailed instructions are most useful and highly appreciated :) )

**Comment by dakra** [comment]
That's strange as `pythonic-activate` only sets the `python-shell-virtualenv-root` variable.
When exactly does this error occur?

Can you do `M-x toggle-debug-on-error` and then do `pythonic-activate` again and post the stacktrace here?

**Comment by kidmose** [comment]
It occurs when I open up emacs and enter `M-x pyenv-mode` or `M-x pythonic-activate`:

This is the content of the `*Backtrace*` (pops up) buffer after `M-x toggle-debug-on-error` and then  `pythonic-activate`:
```
Debugger entered--Lisp error: (file-error "Cannot open load file" "No such file or directory" "f")
  require(f)
  eval-buffer(#<buffer  *load*> nil "/home/egk/.emacs.d/el-get/pythonic/pythonic.el" nil t)  ; Reading at buffer position 1111
  load-with-code-conversion("/home/egk/.emacs.d/el-get/pythonic/pythonic.el" "/home/egk/.emacs.d/el-get/pythonic/pythonic.el" nil t)
  autoload-do-load((autoload "pythonic/pythonic" ("/home/egk/.emacs.d/el-get/.loaddefs.elc" . 173018) t nil) pythonic-activate)
  command-execute(pythonic-activate record)
  execute-extended-command(nil "pythonic-activate" "pythonic-ac")
  funcall-interactively(execute-extended-command nil "pythonic-activate" "pythonic-ac")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

**Comment by kidmose** [comment]
... and if I put `(require 'pyenv-mode)` in my init.el, the errors occurs when I start emacs.

**Comment by kidmose** [comment]
I fixed this by having `el-get` install `f` explicitly.
This doesn't seem like the right solution, but it works.

If someone can provide some guidance on where and how this should be fixed (Including any further debugging), I'm happy to try to prepare a PR. 
If not, I'm also happy with just closing the issue.

Thanks @dakra and other contributors :)

**Comment by CeleritasCelery** [comment]
This seems like an issue with `el-get` because the package lists its dependency on `f.el`. The package manager should download that package as well.
