### ISSUE TITLE
Executable detection broken for some Windows users

### ISSUE THREAD

**Issue by purcell** [proofit404/pythonic#4]
Hi - I received [this bug report](https://github.com/purcell/emacs.d/issues/582#issuecomment-393437380), which appears due to [this code](https://github.com/proofit404/pythonic/blob/c59a158942634d3c07e506b2376d96e8d5d1466f/pythonic.el#L99-L104) in Pythonic.

I'd suggest either the logic be adjusted or - better - you use the `python-shell-interpreter` variable, so that Emacs users can continue to set their Python executable path unambiguously in one place.

**Comment by proofit404** [comment]
Hi, thanks for the report. Will see what I can do.

**Comment by proofit404** [comment]
Should be fixed now.

**Comment by purcell** [comment]
Nice
