### ISSUE TITLE
Maybe replace too specific vagrant detection with generic ssh detection?

### ISSUE THREAD

**Issue by valignatev** [proofit404/pythonic#6]
Detecting vagrant environments is too specific considering it's just a plain old ssh connection which is easily detected by `(pythonic-remote-method)`, which returns `"ssh"`.
We might add ssh-detection, and then replace vagrant detection with it. It might help, for example, with anaconda-mode port forwarding feature in case of generic ssh connection, and not just vagrant. I'll provide a PR, so it'll be clearer what do I mean.

**Comment by valignatev** [comment]
Basically, it's the follow-up for https://github.com/proofit404/anaconda-mode/issues/305. We could replace those with new `pythonic-remote-ssh-p`, or add it to condition with `or`.

**Comment by proofit404** [comment]
I think we can replace the check in the `anaconda-mode` package, but keep predicate function in pythonic. Maybe other packages like `djangonaut` or `edbi-django` will need it in the future.
